# Generated by Django 4.0.2 on 2022-02-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hashtag',
            field=models.ForeignKey(help_text='태그', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.hashtag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='상품 썸네일 이미지', null=True, upload_to='image'),
        ),
    ]
